In [2]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:5],df.iloc[:,-1],test_size=0.4)

In [10]:
X_train

    age  gender  fever   cough       city
34   74    Male  102.0    Mild     Mumbai
39   50  Female  103.0    Mild    Kolkata
66   51    Male  104.0    Mild    Kolkata
31   83    Male  103.0    Mild    Kolkata
96   51  Female  101.0  Strong    Kolkata
12   25  Female   99.0  Strong    Kolkata
79   48  Female  103.0    Mild    Kolkata
93   27    Male  100.0    Mild    Kolkata
23   80  Female   98.0    Mild      Delhi
10   75  Female    NaN    Mild      Delhi
94   79    Male    NaN  Strong    Kolkata
43   22  Female   99.0    Mild  Bangalore
7    20  Female    NaN  Strong     Mumbai
71   75  Female  104.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
41   82    Male    NaN    Mild    Kolkata
65   69  Female  102.0    Mild  Bangalore
29   34  Female    NaN  Strong     Mumbai
64   42    Male  104.0    Mild     Mumbai
74   34  Female  104.0  Strong      Delhi
61   81  Female   98.0  Strong     Mumbai
16   69  Female  103.0    Mild    Kolkata
3    31  Female   98.0    Mild    Kolkata
38   49  Female  101.0    Mild      Delhi
85   16  Female  103.0    Mild  Bangalore
72   83  Female  101.0    Mild    Kolkata
15   70    Male  103.0  Strong    Kolkata
2    42    Male  101.0    Mild      Delhi
86   25    Male  104.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi
89   46    Male  103.0  Strong  Bangalore
33   26  Female   98.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
35   82  Female  102.0  Strong  Bangalore
49   44    Male  104.0    Mild     Mumbai
53   83    Male   98.0    Mild      Delhi
62   56  Female  104.0  Strong  Bangalore
25   23    Male    NaN    Mild     Mumbai
1    27    Male  100.0    Mild      Delhi
14   51    Male  104.0    Mild  Bangalore
80   14  Female   99.0    Mild     Mumbai
8    19  Female  100.0  Strong  Bangalore
27   33  Female  102.0  Strong      Delhi
18   64  Female   98.0    Mild  Bangalore
36   38  Female  101.0    Mild  Bangalore
13   64    Male  102.0    Mild  Bangalore
5    84  Female    NaN    Mild  Bangalore
63   10    Male  100.0    Mild  Bangalore
55   81  Female  101.0    Mild     Mumbai
87   47    Male  101.0  Strong  Bangalore
30   15    Male  101.0    Mild      Delhi
9    64  Female  101.0    Mild      Delhi
68   54  Female  104.0  Strong    Kolkata
83   17  Female  104.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
54   60  Female   99.0    Mild     Mumbai
91   38    Male    NaN    Mild      Delhi
57   49  Female   99.0  Strong  Bangalore
67   65    Male   99.0    Mild  Bangalore
82   24    Male   98.0    Mild    Kolkata

# 1. Aam Zindagi

In [13]:
# adding simple imputer to fever col
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])

#also the test data
X_test_fever=si.fit_transform(X_test[['fever']])

X_train_fever.shape

(60, 1)

In [14]:
# Ordinal Encoding --> Cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(60, 1)

In [16]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(60, 4)

In [17]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(60, 1)

In [ ]:

X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

# Mentos Zindagi

In [19]:
from sklearn.compose import ColumnTransformer

In [24]:

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [25]:

transformer.fit_transform(X_train).shape

(60, 7)

In [26]:

transformer.transform(X_test).shape

(40, 7)